### PR TITLE
Added !default to variables to easily override them

### PR DESCRIPTION
**Pull request by rafaeelaudibert**
Added !default in all the applicable rules, as well as used merge-map to create !default maps.
This way we can easily override any variable if needed to.

As I'm new to the tabler ecosystem, and only used this gem, I don't know if this is supposed to be updated upstream as well. If needed, please comment all the places I should send this changes

### CODE REVIEW

**Comment by lightyrs** [comment]
@rafaeelaudibert Thank you, however, one thing that's required for modifications to this gem is that your changes will work with the update rake task (that pulls down new tabler assets). Please modify this PR so that the update task will add any of these changes.

**Comment by rafaeelaudibert** [comment]
This means I need to update this on the upstream (default tabler branch), so keep this on hold, as soon as they merge my PR we can merge this too

**Comment by lightyrs** [comment]
> This means I need to update this on the upstream (default tabler branch), so keep this on hold, as soon as they merge my PR we can merge this too

You can just have the update task edit the tabler file after it's pulled down. That's what we currently do. @rafaeelaudibert

**Comment by rafaeelaudibert** [comment]
I think that's kinda hard, as I need to check some special cases with the maps. I think it would be easier to update in the tabler gem itself, as it wouldn't clutch this code that much

**Pull request closed without merging**
