### PR TITLE
Rename plugin.css files to plugin.scss

### PR DESCRIPTION
**Pull request by tryice3**
In order to be able to use config.assets.compile = false on production without any issues the plugin.css files are renamed to plugin.scss.

### CODE REVIEW

**Comment by lightyrs** [comment]
@fibice3 Thanks for the PR. Does this PR require any changes to the README? Does it change any existing behavior with regard to imports?

**Comment by tryice3** [comment]
I modified the README.
The only difference is that there are no more .css files, they are replaced with .scss

**Comment by lightyrs** [comment]
@fibice3 This is good, however, it breaks the `rake:update` task that updates the gem with upstream tabler assets. Can you please modify the `Updater` class (specifically `Updater::SCSS`) to incorporate your changes? 

The relevant code is here: 
https://github.com/lightyrs/tabler-rubygem/blob/master/tasks/updater/scss.rb

Thank you.

**Comment by tryice3** [comment]
I changed the scss.rb.

**Comment by lightyrs** [comment]
@fibice3 I'll merge this by end of weekend.

**Comment by IbrahimSerhat** [comment]
It's ok, pull please.

**Comment by lightyrs** [comment]
@fibice3 @IbrahimSerhat This is merged. Thank you for the contribution 🙏

**Pull request merged**
